version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/app/.env
    ports:
      - "8000:8000"
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4173:4173"

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    # For persistent storage, add:
    # volumes:
    #   - redis-data:/data

# Uncomment for persistent Redis storage
# volumes:
#   redis-data:
