import os
from dotenv import load_dotenv

load_dotenv()

REDIS_HOST = "redis"
REDIS_PORT = 6379

SPOTIFY_CLIENT_ID = os.getenv("SPOTIFY_CLIENT_ID")
SPOTIFY_CLIENT_SECRET = os.getenv("SPOTIFY_CLIENT_SECRET")
SPOTIFY_REDIRECT_URI = os.getenv("SPOTIFY_REDIRECT_URI")

TICKETMASTER_API = os.getenv("TICKETMASTER_API_KEY")